# Generated by Django 5.0.3 on 2024-05-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
