# Generated by Django 5.0.3 on 2024-05-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_product_images_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_images',
        ),
    ]
