# Generated by Django 5.0.3 on 2024-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adresse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
