# Generated by Django 4.2.5 on 2024-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0003_alter_product_seller_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
