# Generated by Django 4.2.5 on 2024-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0004_alter_product_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
