# Generated by Django 4.2.5 on 2024-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0005_alter_product_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='All', max_length=20),
        ),
    ]
