# Generated by Django 5.0.3 on 2024-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
