# Generated by Django 5.0.4 on 2024-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0007_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
