# Generated by Django 4.2.5 on 2024-05-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0007_alter_product_id_alter_product_images_id'),
        ('product_manager', '0008_alter_product_images_id'),
    ]

    operations = [
    ]
